'------------------------------------------------------------------------------
' <auto-generated>
'     このコードはテンプレートから生成されました。
'
'     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
'     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class m_code
    Public Property code_bunrui As String
    Public Property code_value As String
    Public Property code_text As String
    Public Property start_date As Nullable(Of Date)
    Public Property end_date As Nullable(Of Date)

End Class
