'------------------------------------------------------------------------------
' <auto-generated>
'     このコードはテンプレートから生成されました。
'
'     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
'     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class m_user
    Public Property user_id As String
    Public Property user_name As String
    Public Property address As String
    Public Property note As String
    Public Property regist_datetime As Nullable(Of Date)

End Class
